# Generated by Django 3.0.5 on 2020-04-28 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscrape', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comic_title', models.CharField(max_length=100)),
                ('comic_type', models.CharField(max_length=100)),
                ('s3_bucket_link', models.TextField()),
            ],
        ),
    ]
