# Generated by Django 3.0.5 on 2020-04-29 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webscrape', '0003_auto_20200429_0047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comics',
            old_name='image_link',
            new_name='comic_link',
        ),
    ]
