# Generated by Django 3.0.5 on 2020-04-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscrape', '0005_titles'),
    ]

    operations = [
        migrations.AddField(
            model_name='titles',
            name='comic_catalog',
            field=models.TextField(default=None),
        ),
    ]
